typography_spectrum: 0.2254253977444023
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2527224908117205
  lightness: 0.9434975311160088
  saturation: 0.5857380446977913
  rhythmicContrast: 0.19547497224994004
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.674062489066273
analytics:
  google: null
  facebook: null
  twitter: null
name: Margo & Todd
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Margo loves Todd. Todd loves Margo.
description: Make mindfulness minful again.
purpose: []
